export interface Experience {
    id?: string; // Optional, as it will be generated by MongoDB
    title: string;
    subtitle: string;
    location: string;
    dates: string; // Format: e.g., "January 2020 - Present"
    order: number; // Default is 0
    info: string[]; // Array of strings
    image: string; 
    createdAt?: string; // Optional, added by Mongoose timestamps
    updatedAt?: string; // Optional, added by Mongoose timestamps
}